"""empty message

Revision ID: 7e4e56e6fcef
Revises: 1a4dafd0f533
Create Date: 2026-09-11 03:09:05.705199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e4e56e6fcef'
down_revision: Union[str, Sequence[str], None] = '1a4dafd0f533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'chat_type',
               existing_type=postgresql.ENUM('DIRECT', 'GROUP', name='chattype'),
               type_=sa.Enum('DIRECT', 'GROUP', name='chattype', schema='public', inherit_schema=True),
               existing_nullable=False)
    op.drop_constraint(op.f('chat_participant_chat_id_fkey'), 'chat_participant', type_='foreignkey')
    op.drop_constraint(op.f('chat_participant_user_id_fkey'), 'chat_participant', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participant', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'chat_participant', 'chat', ['chat_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_senderId_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_chatId_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['senderId'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'messages', 'chat', ['chatId'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('readstatus_user_id_fkey'), 'readstatus', type_='foreignkey')
    op.drop_constraint(op.f('readstatus_chat_id_fkey'), 'readstatus', type_='foreignkey')
    op.create_foreign_key(None, 'readstatus', 'chat', ['chat_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'readstatus', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readstatus', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'readstatus', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('readstatus_chat_id_fkey'), 'readstatus', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('readstatus_user_id_fkey'), 'readstatus', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chatId_fkey'), 'messages', 'chat', ['chatId'], ['id'])
    op.create_foreign_key(op.f('messages_senderId_fkey'), 'messages', 'users', ['senderId'], ['id'])
    op.drop_constraint(None, 'chat_participant', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'chat_participant', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('chat_participant_user_id_fkey'), 'chat_participant', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_participant_chat_id_fkey'), 'chat_participant', 'chat', ['chat_id'], ['id'])
    op.alter_column('chat', 'chat_type',
               existing_type=sa.Enum('DIRECT', 'GROUP', name='chattype', schema='public', inherit_schema=True),
               type_=postgresql.ENUM('DIRECT', 'GROUP', name='chattype'),
               existing_nullable=False)
    # ### end Alembic commands ###
